export const compositionList = [
  {
    name: 'Japan post demo',
    ago: '2 days',
    key: 'r9DfPqMsH',
    details: {
      data: {
        name: 'Japan post demo',
        dsl: `import vision
  import planning
  import ik
  import motioncontrol
  import motionoptimizer
  
  # load a scene from hardware catalogue
  planning_scene = CreatePlanningScene("warehouse1")
  
  # get cameras, empty list if no cameras are present
  cameras = planning_scene.getCameras()
  
  # get robots
  robots = planning_scene.getRobots()
  robot = robots.GetRobot()[0]
  
  #load model to be detected
  vision.loadModel("primitive_box")
  repeat = 0
  while (repeat < 10):
      
      #detect from one of the camera, throws error
      try:
          objects = vision.getObjects([cameras[0]])
      except NoCameraFound:
          debug_print("Requested camera not found!")
      if not objects:
          exit
          
      path = planning.plan(planning_scene, robot, objects[0])
      
      # If path is not found, enable debug to visually debug the cause
      if not path:
          error_print("Path not found")
          auto_visual_debug(true) # user can interact with the environment to debug the issue
      
      robot.execute(path)
      
      place_location = planning_scene.getPlaceLocation()
      path = planning.plan(planning_scene, robot, place_location)
      
      # If path is not found, enable debug to visually debug the cause
      if not path:
          error_print("Path not found")
          auto_visual_debug(true) # user can interact with the environment to debug the issue
      robot.execute(path)
      
      repeat += 1
      
      
      
      `,
        last_modified: '2019-01-01T11:28:56.197234Z',
        environment: {
          urdf: `<?xml version="1.0" ?>
  <!-- =================================================================================== -->
  <!-- |    This document was autogenerated by xacro from japanpost_env_schmalz_multisuction.urdf.xacro | -->
  <!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
  <!-- =================================================================================== -->
  <robot name="japanpost_environment" xmlns:xacro="http://ros.org/wiki/xacro">
    <gazebo>
      <plugin filename="libgazebo_ros_control.so" name="ros_control">
        <!--robotNamespace>/</robotNamespace-->
        <!--robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType-->
      </plugin>
      <!--
      <plugin name="gazebo_ros_power_monitor_controller" filename="libgazebo_ros_power_monitor.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>1.0</updateRate>
        <timeout>5</timeout>
        <powerStateTopic>power_state</powerStateTopic>
        <powerStateRate>10.0</powerStateRate>
        <fullChargeCapacity>87.78</fullChargeCapacity>     
        <dischargeRate>-474</dischargeRate>
        <chargeRate>525</chargeRate>
        <dischargeVoltage>15.52</dischargeVoltage>
        <chargeVoltage>16.41</chargeVoltage>
      </plugin>
  -->
    </gazebo>
    <!--
    Author: Kelsey Hawkins
    Contributers: Jimmy Da Silva, Ajit Krisshna N L, Muhammad Asif Rana
  -->
    <!-- measured from model -->
    <material name="Grey">
      <color rgba="0.7 0.7 0.7 1.0"/>
    </material>
    <material name="GreyPallet">
      <color rgba="0.7 0.7 0.7 1.0"/>
    </material>
    <material name="Grey4">
      <color rgba="0.6 0.7 0.8 1.0"/>
    </material>
    <material name="Grey2">
      <color rgba="0.7 0.7 0.7 1.0"/>
    </material>
    <link name="japanpost_environment"/>
    <joint name="japanpost_environment_jp_table_base_joint" type="fixed">
      <origin rpy="0.0 0.0 0.0" xyz="0 0 0.75"/>
      <parent link="japanpost_environment"/>
      <child link="jp_table_link"/>
    </joint>
    <link name="jp_table_link">
      <visual>
        <geometry>
          <mesh filename="package://rr_world_description/meshes/rr_japanpost_parts/table_frame_camera_v.stl"/>
        </geometry>
        <material name="Grey"/>
      </visual>
      <!--collision>
        <geometry>
          <mesh filename="package://rr_world_description/meshes/rr_japanpost_parts/table_frame_camera_v.stl"/>
        </geometry>
      </collision-->
      <collision>
        <origin rpy="0 0 0" xyz="0 0 -0.37"/>
        <geometry>
          <box size="0.77 0.77 0.77"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="0 0 0" xyz="0 0.32 0.73"/>
        <geometry>
          <box size="0.77 0.14 1.8"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="0 0 0" xyz="-0.73 0.08 1.525"/>
        <geometry>
          <box size="0.8 0.77 0.13"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="-0.785 0 0" xyz="0.355 0.15 0.13"/>
        <geometry>
          <box size="0.05 0.05 0.5"/>
        </geometry>
      </collision>
    </link>
    <gazebo reference="jp_table_link">
      <static>true</static>
    </gazebo>
    <joint name="japanpost_environment_jp_pallet_base_joint" type="planar">
      <origin rpy="0.0 0.0 -1.57" xyz="-1.10 -0.25 0"/>
      <parent link="japanpost_environment"/>
      <child link="jp_pallet_link"/>
    </joint>
    <link name="jp_pallet_link">
      <visual>
        <geometry>
          <mesh filename="package://rr_world_description/meshes/rr_japanpost_parts/roll_pallet_v.stl"/>
        </geometry>
        <material name="GreyPallet"/>
      </visual>
      <!--collision>
        <geometry>
          <mesh filename="package://rr_world_description/meshes/rr_japanpost_parts/roll_pallet_v.stl"/>
        </geometry>
      </collision-->
      <collision>
        <origin rpy="0 0 0" xyz="0 -0.34 1.1"/>
        <geometry>
          <box size="1.27 0.08 1.9"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="0 0 0" xyz="0.62 0.02 1.1"/>
        <geometry>
          <box size="0.2 0.74 1.9"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="0 0 0" xyz="-0.61 0.02 1.1"/>
        <geometry>
          <box size="0.2 0.74 1.9"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="0 0 0" xyz="0 0.01 0.15"/>
        <geometry>
          <box size="1.27 0.75 0.27"/>
        </geometry>
      </collision>
    </link>
    <gazebo reference="jp_pallet_link">
      <static>true</static>
    </gazebo>
    <joint name="japanpost_environment_jp_conveyor_base_joint" type="fixed">
      <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
      <parent link="japanpost_environment"/>
      <child link="jp_conveyor_link"/>
    </joint>
    <link name="jp_conveyor_link">
      <visual>
        <geometry>
          <mesh filename="package://rr_world_description/meshes/rr_japanpost_parts/dummy_conveyor.stl"/>
        </geometry>
        <material name="Grey4"/>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://rr_world_description/meshes/rr_japanpost_parts/dummy_conveyor.stl"/>
        </geometry>
      </collision>
      <!--collision>
        <origin xyz="0.0 1 -0.03" rpy="0 0 0"/>
        <geometry>
          <box size="0.64 2.1 0.16"/>
        </geometry>
      </collision-->
    </link>
    <gazebo reference="jp_conveyor_link">
      <static>true</static>
    </gazebo>
    <link name="agv_base_link">
      <visual>
        <origin rpy="0.0 0 1.57" xyz="0 0 -0.13"/>
        <geometry>
          <!--<box size="1.03 0.6 0.04"/>-->
          <!--<mesh filename="package://rr_shared_world_description/meshes/ifollow_agv/nowheels_robot.stl" scale="0.001 0.001 0.001"/>-->
          <mesh filename="package://rr_shared_world_description/meshes/ifollow_agv/fancy_agv.dae" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <box size="1.03 0.63 0.04"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="80"/>
        <inertia ixx="2.66" ixy="0.0" ixz="0.0" iyy="7.08" iyz="0.0" izz="9.72"/>
      </inertial>
    </link>
    <joint name="agv_base_link_left_wheel_joint" type="continuous">
      <origin rpy="-1.57 0.0 0.0" xyz="0.0 0.329 -0.055"/>
      <parent link="agv_base_link"/>
      <child link="left_wheel_link"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.01" friction="0.5"/>
    </joint>
    <link name="left_wheel_link">
      <visual>
        <geometry>
          <cylinder length="0.046" radius="0.075"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.046" radius="0.075"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="2.5"/>
        <inertia ixx="0.00395645833333" ixy="0.0" ixz="0.0" iyy="0.00395645833333" iyz="0.0" izz="0.00703125"/>
      </inertial>
      <surface>
        <friction>
          <ode>
            <mu>0.1</mu>
            <mu2>0.1</mu2>
          </ode>
        </friction>
      </surface>
    </link>
    <transmission name="agv_base_link_left_wheel_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="agv_base_link_left_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="agv_base_link_left_wheel_actuator">
        <mechanicalReduction>6.75</mechanicalReduction>
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    <joint name="agv_base_link_right_wheel_joint" type="continuous">
      <origin rpy="-1.57 0.0 0.0" xyz="0.0 -0.329 -0.055"/>
      <parent link="agv_base_link"/>
      <child link="right_wheel_link"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.01" friction="0.5"/>
    </joint>
    <link name="right_wheel_link">
      <visual>
        <geometry>
          <cylinder length="0.046" radius="0.075"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.046" radius="0.075"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="2.5"/>
        <inertia ixx="0.00395645833333" ixy="0.0" ixz="0.0" iyy="0.00395645833333" iyz="0.0" izz="0.00703125"/>
      </inertial>
      <surface>
        <friction>
          <ode>
            <mu>0.1</mu>
            <mu2>0.1</mu2>
          </ode>
        </friction>
      </surface>
    </link>
    <transmission name="agv_base_link_right_wheel_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="agv_base_link_right_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="agv_base_link_right_wheel_actuator">
        <mechanicalReduction>6.75</mechanicalReduction>
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    <link name="front_left_wheel_caster_link">
      <visual>
        <geometry>
          <sphere radius="0.01"/>
          <!--<box size="0.01 0.01 0.01"/>-->
        </geometry>
      </visual>
      <collision>
        <geometry>
          <sphere radius="0.01"/>
          <!--<box size="0.01 0.01 0.01"/>-->
        </geometry>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.0002" iyz="0.0" izz="0.0002"/>
      </inertial>
    </link>
    <joint name="front_left_wheel_pitch" type="continuous">
      <parent link="agv_base_link"/>
      <child link="front_left_wheel_caster_link"/>
      <origin rpy="0.0 0.0 0.0" xyz="0.515 0.315 -0.035"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.003" friction="0.08"/>
    </joint>
    <transmission name="front_left_wheel_pitch_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="front_left_wheel_pitch">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="front_left_wheel_pitch_actuator">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    <joint name="front_left_wheel_caster_link_front_left_wheel_joint" type="continuous">
      <origin rpy="1.57 1.57 0" xyz="-0.04 0 -0.06"/>
      <parent link="front_left_wheel_caster_link"/>
      <child link="front_left_wheel_link"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.01" friction="0.5"/>
    </joint>
    <link name="front_left_wheel_link">
      <visual>
        <geometry>
          <cylinder length="0.053" radius="0.035"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.053" radius="0.035"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.25"/>
        <inertia ixx="0.000675416666667" ixy="0.0" ixz="0.0" iyy="0.000675416666667" iyz="0.0" izz="0.000765625"/>
      </inertial>
      <surface>
        <friction>
          <ode>
            <mu>0.1</mu>
            <mu2>0.1</mu2>
          </ode>
        </friction>
      </surface>
    </link>
    <transmission name="front_left_wheel_caster_link_front_left_wheel_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="front_left_wheel_caster_link_front_left_wheel_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="front_left_wheel_caster_link_front_left_wheel_actuator">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    <link name="front_right_wheel_caster_link">
      <visual>
        <geometry>
          <sphere radius="0.01"/>
          <!--<box size="0.01 0.01 0.01"/>-->
        </geometry>
      </visual>
      <collision>
        <geometry>
          <sphere radius="0.01"/>
          <!--<box size="0.01 0.01 0.01"/>-->
        </geometry>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.0002" iyz="0.0" izz="0.0002"/>
      </inertial>
    </link>
    <joint name="front_right_wheel_pitch" type="continuous">
      <parent link="agv_base_link"/>
      <child link="front_right_wheel_caster_link"/>
      <origin rpy="0.0 0.0 0.0" xyz="0.515 -0.315 -0.035"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.003" friction="0.08"/>
    </joint>
    <transmission name="front_right_wheel_pitch_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="front_right_wheel_pitch">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="front_right_wheel_pitch_actuator">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    <joint name="front_right_wheel_caster_link_front_right_wheel_joint" type="continuous">
      <origin rpy="1.57 1.57 0" xyz="-0.04 0 -0.06"/>
      <parent link="front_right_wheel_caster_link"/>
      <child link="front_right_wheel_link"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.01" friction="0.5"/>
    </joint>
    <link name="front_right_wheel_link">
      <visual>
        <geometry>
          <cylinder length="0.053" radius="0.035"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.053" radius="0.035"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.25"/>
        <inertia ixx="0.000675416666667" ixy="0.0" ixz="0.0" iyy="0.000675416666667" iyz="0.0" izz="0.000765625"/>
      </inertial>
      <surface>
        <friction>
          <ode>
            <mu>0.1</mu>
            <mu2>0.1</mu2>
          </ode>
        </friction>
      </surface>
    </link>
    <transmission name="front_right_wheel_caster_link_front_right_wheel_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="front_right_wheel_caster_link_front_right_wheel_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="front_right_wheel_caster_link_front_right_wheel_actuator">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    <link name="back_left_wheel_caster_link">
      <visual>
        <geometry>
          <sphere radius="0.01"/>
          <!--<box size="0.01 0.01 0.01"/>-->
        </geometry>
      </visual>
      <collision>
        <geometry>
          <sphere radius="0.01"/>
          <!--<box size="0.01 0.01 0.01"/>-->
        </geometry>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.0002" iyz="0.0" izz="0.0002"/>
      </inertial>
    </link>
    <joint name="back_left_wheel_pitch" type="continuous">
      <parent link="agv_base_link"/>
      <child link="back_left_wheel_caster_link"/>
      <origin rpy="0.0 0.0 0.0" xyz="-0.515 0.315 -0.035"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.003" friction="0.08"/>
    </joint>
    <transmission name="back_left_wheel_pitch_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="back_left_wheel_pitch">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="back_left_wheel_pitch_actuator">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    <joint name="back_left_wheel_caster_link_back_left_wheel_joint" type="continuous">
      <origin rpy="1.57 1.57 0" xyz="-0.04 0 -0.06"/>
      <parent link="back_left_wheel_caster_link"/>
      <child link="back_left_wheel_link"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.01" friction="0.5"/>
    </joint>
    <link name="back_left_wheel_link">
      <visual>
        <geometry>
          <cylinder length="0.053" radius="0.035"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.053" radius="0.035"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.25"/>
        <inertia ixx="0.000675416666667" ixy="0.0" ixz="0.0" iyy="0.000675416666667" iyz="0.0" izz="0.000765625"/>
      </inertial>
      <surface>
        <friction>
          <ode>
            <mu>0.1</mu>
            <mu2>0.1</mu2>
          </ode>
        </friction>
      </surface>
    </link>
    <transmission name="back_left_wheel_caster_link_back_left_wheel_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="back_left_wheel_caster_link_back_left_wheel_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="back_left_wheel_caster_link_back_left_wheel_actuator">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    <link name="back_right_wheel_caster_link">
      <visual>
        <geometry>
          <sphere radius="0.01"/>
          <!--<box size="0.01 0.01 0.01"/>-->
        </geometry>
      </visual>
      <collision>
        <geometry>
          <sphere radius="0.01"/>
          <!--<box size="0.01 0.01 0.01"/>-->
        </geometry>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.0002" iyz="0.0" izz="0.0002"/>
      </inertial>
    </link>
    <joint name="back_right_wheel_pitch" type="continuous">
      <parent link="agv_base_link"/>
      <child link="back_right_wheel_caster_link"/>
      <origin rpy="0.0 0.0 0.0" xyz="-0.515 -0.315 -0.035"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.003" friction="0.08"/>
    </joint>
    <transmission name="back_right_wheel_pitch_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="back_right_wheel_pitch">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="back_right_wheel_pitch_actuator">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    <joint name="back_right_wheel_caster_link_back_right_wheel_joint" type="continuous">
      <origin rpy="1.57 1.57 0" xyz="-0.04 0 -0.06"/>
      <parent link="back_right_wheel_caster_link"/>
      <child link="back_right_wheel_link"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.01" friction="0.5"/>
    </joint>
    <link name="back_right_wheel_link">
      <visual>
        <geometry>
          <cylinder length="0.053" radius="0.035"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.053" radius="0.035"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.25"/>
        <inertia ixx="0.000675416666667" ixy="0.0" ixz="0.0" iyy="0.000675416666667" iyz="0.0" izz="0.000765625"/>
      </inertial>
      <surface>
        <friction>
          <ode>
            <mu>0.1</mu>
            <mu2>0.1</mu2>
          </ode>
        </friction>
      </surface>
    </link>
    <transmission name="back_right_wheel_caster_link_back_right_wheel_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="back_right_wheel_caster_link_back_right_wheel_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="back_right_wheel_caster_link_back_right_wheel_actuator">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    <gazebo reference="agv_base_link">
      <material>Gazebo/Grey3</material>
    </gazebo>
    <gazebo>
      <plugin filename="libgazebo_ros_control.so" name="gazebo_ros_control">
        <robotNamespace>/</robotNamespace>
      </plugin>
    </gazebo>
    <joint name="agv_joint" type="planar">
      <parent link="japanpost_environment"/>
      <child link="agv_base_link"/>
      <origin rpy="0.0 0.0 3.14" xyz="-1.10 -0.25 0.15"/>
    </joint>
    <link name="base_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/base.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/collision/base.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="4.0"/>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <inertia ixx="0.0061063308908" ixy="0.0" ixz="0.0" iyy="0.0061063308908" iyz="0.0" izz="0.01125"/>
      </inertial>
    </link>
    <joint name="shoulder_pan_joint" type="revolute">
      <parent link="base_link"/>
      <child link="shoulder_link"/>
      <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.1273"/>
      <axis xyz="0 0 1"/>
      <limit effort="330.0" lower="0.0" upper="3.14159265359" velocity="2.16"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="shoulder_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/shoulder.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/collision/shoulder.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="7.778"/>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <inertia ixx="0.0314743125769" ixy="0.0" ixz="0.0" iyy="0.0314743125769" iyz="0.0" izz="0.021875625"/>
      </inertial>
    </link>
    <joint name="shoulder_lift_joint" type="revolute">
      <parent link="shoulder_link"/>
      <child link="upper_arm_link"/>
      <origin rpy="0.0 1.57079632679 0.0" xyz="0.0 0.220941 0.0"/>
      <axis xyz="0 1 0"/>
      <limit effort="330.0" lower="-3.14159265359" upper="0.0" velocity="2.16"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="upper_arm_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/upperarm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/collision/upperarm.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="12.93"/>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.306"/>
        <inertia ixx="0.421753803798" ixy="0.0" ixz="0.0" iyy="0.421753803798" iyz="0.0" izz="0.036365625"/>
      </inertial>
    </link>
    <joint name="elbow_joint" type="revolute">
      <parent link="upper_arm_link"/>
      <child link="forearm_link"/>
      <origin rpy="0.0 0.0 0.0" xyz="0.0 -0.1719 0.612"/>
      <axis xyz="0 1 0"/>
      <limit effort="150.0" lower="-3.14159265359" upper="3.14159265359" velocity="3.15"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="forearm_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/forearm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/collision/forearm.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="3.87"/>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.28615"/>
        <inertia ixx="0.111069694097" ixy="0.0" ixz="0.0" iyy="0.111069694097" iyz="0.0" izz="0.010884375"/>
      </inertial>
    </link>
    <joint name="wrist_1_joint" type="revolute">
      <parent link="forearm_link"/>
      <child link="wrist_1_link"/>
      <origin rpy="0.0 1.57079632679 0.0" xyz="0.0 0.0 0.5723"/>
      <axis xyz="0 1 0"/>
      <limit effort="54.0" lower="-3.14159265359" upper="0.785398163397" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="wrist_1_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/wrist1.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/collision/wrist1.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.96"/>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <inertia ixx="0.0051082479567" ixy="0.0" ixz="0.0" iyy="0.0051082479567" iyz="0.0" izz="0.0055125"/>
      </inertial>
    </link>
    <joint name="wrist_2_joint" type="revolute">
      <parent link="wrist_1_link"/>
      <child link="wrist_2_link"/>
      <origin rpy="0.0 0.0 0.0" xyz="0.0 0.1149 0.0"/>
      <axis xyz="0 0 1"/>
      <limit effort="54.0" lower="-3.14159265359" upper="0.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="wrist_2_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/wrist2.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/collision/wrist2.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.96"/>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <inertia ixx="0.0051082479567" ixy="0.0" ixz="0.0" iyy="0.0051082479567" iyz="0.0" izz="0.0055125"/>
      </inertial>
    </link>
    <joint name="wrist_3_joint" type="revolute">
      <parent link="wrist_2_link"/>
      <child link="wrist_3_link"/>
      <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.1157"/>
      <axis xyz="0 1 0"/>
      <limit effort="54.0" lower="2.09439510239" upper="4.71238898038" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="wrist_3_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/wrist3.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur10/collision/wrist3.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.202"/>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <inertia ixx="0.000526462289415" ixy="0.0" ixz="0.0" iyy="0.000526462289415" iyz="0.0" izz="0.000568125"/>
      </inertial>
    </link>
    <joint name="ee_fixed_joint" type="fixed">
      <parent link="wrist_3_link"/>
      <child link="ee_link"/>
      <origin rpy="0.0 0.0 1.57079632679" xyz="0.0 0.0922 0.0"/>
    </joint>
    <link name="ee_link">
      <collision>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.01 0 0"/>
      </collision>
    </link>
    <transmission name="shoulder_pan_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="shoulder_pan_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="shoulder_pan_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <transmission name="shoulder_lift_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="shoulder_lift_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="shoulder_lift_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <transmission name="elbow_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="elbow_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="elbow_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <transmission name="wrist_1_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="wrist_1_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="wrist_1_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <transmission name="wrist_2_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="wrist_2_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="wrist_2_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <transmission name="wrist_3_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="wrist_3_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="wrist_3_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <!-- nothing to do here at the moment -->
    <!-- ROS base_link to UR 'Base' Coordinates transform -->
    <link name="base"/>
    <joint name="base_link-base_fixed_joint" type="fixed">
      <!-- NOTE: this rotation is only needed as long as base_link itself is
                   not corrected wrt the real robot (ie: rotated over 180
                   degrees)
        -->
      <origin rpy="0 0 -3.14159265359" xyz="0 0 0"/>
      <parent link="base_link"/>
      <child link="base"/>
    </joint>
    <!-- Frame coincident with all-zeros TCP on UR controller -->
    <link name="tool0"/>
    <joint name="wrist_3_link-tool0_fixed_joint" type="fixed">
      <origin rpy="-1.57079632679 0 0" xyz="0 0.0922 0"/>
      <parent link="wrist_3_link"/>
      <child link="tool0"/>
    </joint>
    <joint name="ur10_joint" type="fixed">
      <parent link="jp_table_link"/>
      <child link="base_link"/>
      <origin rpy="0.0 0.0 1.57" xyz="0.0 0.0 0.0"/>
    </joint>
    <joint name="tool0_schmalz_gripper_gripper_joint" type="fixed">
      <origin rpy="0.0 0.0 0.345" xyz="0.0 0.0 0.05"/>
      <parent link="tool0"/>
      <child link="schmalz_gripper_link"/>
    </joint>
    <link name="schmalz_gripper_link">
      <visual>
        <geometry>
          <mesh filename="package://rr_world_description/meshes/rr_schmalz_multisuction/schmalz_visual.stl"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://rr_world_description/meshes/rr_schmalz_multisuction/schmalz_visual.stl"/>
          <!--box size="0.29 0.17 0.2"/-->
        </geometry>
      </collision>
      <!--collision for the wires to gripper-->
      <collision>
        <origin rpy="0.0 0.0 0.0" xyz="0.13 -0.01 -0.125"/>
        <geometry>
          <box size="0.02 0.10 0.25"/>
        </geometry>
      </collision>
    </link>
    <!-- tool center point -->
    <link name="tool_center_point"/>
    <joint name="tool_center_point_joint" type="fixed">
      <parent link="tool0"/>
      <child link="tool_center_point"/>
      <origin rpy="0.0 0.0 0.345" xyz="0.0 0.0 0.125"/>
    </joint>
  </robot>`,
          packages: {
            robotiq_2f_model: 'https://storage.googleapis.com/kompose-artifacts/robotiq_2f_model',
            rr_world_description: 'https://storage.googleapis.com/kompose-artifacts/rr_world_description',
            ur_description: 'https://storage.googleapis.com/kompose-artifacts/ur_description',
            rr_japanpost_parts: 'https://storage.googleapis.com/kompose-artifacts/rr_japanpost_parts',
            rr_schmalz_multisuction: 'https://storage.googleapis.com/kompose-artifacts/rr_schmalz_multisuction',
            mitsubishi_manipulator_description:
                'https://storage.googleapis.com/kompose-artifacts/mitsubishi_manipulator_description',
            nkc_amr_description: 'https://storage.googleapis.com/kompose-artifacts/nkc_amr_description',
            rr_shared_world_description: 'https://storage.googleapis.com/kompose-artifacts/rr_shared_world_description',
          },
          last_modified: '2019-01-01T11:19:52.958376Z',
          last_modified_by: {
            userid: '123',
            username: 'guest4',
          },
          is_locked: false,
          locked_by: {
            userid: '123',
            username: 'guest4',
          },
        },
      },
    }
  },
  {
    name: 'Mitsubishi demo',
    ago: '20 hours',
    key: 'vcqD7cFggx',
    details: {
      data: {
        name: 'Mitsubishi demo',
        dsl: `
      
      `,
        last_modified: '2019-01-01T11:28:56.197234Z',
        environment: {
          urdf: `<?xml version="1.0" ?>
  <!-- =================================================================================== -->
  <!-- |    This document was autogenerated by xacro from mitsubishi_rv4frl.robot.urdf.xacro | -->
  <!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
  <!-- =================================================================================== -->
  <robot name="mitsubishi_rv4frl" xmlns:xacro="http://ros.org/wiki/xacro">
    <gazebo>
      <plugin filename="libgazebo_ros_control.so" name="ros_control">
        <!--robotNamespace>/</robotNamespace-->
        <!--robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType-->
      </plugin>
      <!--
      <plugin name="gazebo_ros_power_monitor_controller" filename="libgazebo_ros_power_monitor.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>1.0</updateRate>
        <timeout>5</timeout>
        <powerStateTopic>power_state</powerStateTopic>
        <powerStateRate>10.0</powerStateRate>
        <fullChargeCapacity>87.78</fullChargeCapacity>     
        <dischargeRate>-474</dischargeRate>
        <chargeRate>525</chargeRate>
        <dischargeVoltage>15.52</dischargeVoltage>
        <chargeVoltage>16.41</chargeVoltage>
      </plugin>
  -->
    </gazebo>
    <!--
    Author: Denny Boby
  -->
    <!--Change according to your need-->
    <link name="base_link">
      <visual>
        <geometry>
          <mesh filename="package://mitsubishi_manipulator_description/meshes/rv4frl/base_link.STL"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://mitsubishi_manipulator_description/meshes/rv4frl/base_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="0.034625 0.093511 -0.0084524"/>
        <mass value="8.5403"/>
        <inertia ixx="0.049098" ixy="0.002252" ixz="-0.0027071" iyy="0.069554" iyz="0.00047187" izz="0.069527"/>
      </inertial>
    </link>
    <joint name="joint1" type="revolute">
      <parent link="base_link"/>
      <child link="shoulder_link"/>
      <origin rpy="1.5708 0 0" xyz="0 0 0.35"/>
      <axis xyz="0 1 0"/>
      <limit effort="224.64" lower="-4.18879020479" upper="4.18879020479" velocity="7.33038285838"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="shoulder_link">
      <visual>
        <geometry>
          <mesh filename="package://mitsubishi_manipulator_description/meshes/rv4frl/shoulder_link.STL"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://mitsubishi_manipulator_description/meshes/rv4frl/shoulder_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="-0.0068142 -0.060831 0.0013335"/>
        <mass value="3.7141"/>
        <inertia ixx="0.038649" ixy="-0.0011249" ixz="-5.4756E-05" iyy="0.027659" iyz="-0.00021678" izz="0.02291"/>
      </inertial>
    </link>
    <joint name="joint2" type="revolute">
      <parent link="shoulder_link"/>
      <child link="armone_link"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="263.25" lower="-2.09439510239" upper="2.09439510239" velocity="5.8643062867"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="armone_link">
      <visual>
        <geometry>
          <mesh filename="package://mitsubishi_manipulator_description/meshes/rv4frl/armone_link.STL"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://mitsubishi_manipulator_description/meshes/rv4frl/armone_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="0.015356 0.10443 0.00033139"/>
        <mass value="5.5316"/>
        <inertia ixx="0.086565" ixy="-0.0025205" ixz="-4.249E-05" iyy="0.020114" iyz="-0.00039674" izz="0.079688"/>
      </inertial>
    </link>
    <joint name="joint3" type="revolute">
      <parent link="armone_link"/>
      <child link="elbow_link"/>
      <origin rpy="0 0 -1.57" xyz="0 0.31 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="145.15" lower="0" upper="2.86233997327" velocity="4.36332312999"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="elbow_link">
      <visual>
        <geometry>
          <mesh filename="package://mitsubishi_manipulator_description/meshes/rv4frl/elbow_link.STL"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://mitsubishi_manipulator_description/meshes/rv4frl/elbow_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="0.00434612569963741 0.0195661756993112 0.00034525741506525"/>
        <mass value="2.25803701418"/>
        <inertia ixx="0.00644975213242616" ixy="0.0004176954649227" ixz="4.04694801218676E-05" iyy="0.00576092457676823" iyz="2.02577048707337E-05" izz="0.00689520125677162"/>
      </inertial>
    </link>
    <joint name="joint4" type="revolute">
      <parent link="elbow_link"/>
      <child link="armtwo_link"/>
      <origin rpy="3.1416 0 0" xyz="-0.335 0.05 0"/>
      <axis xyz="-1 0 0"/>
      <limit effort="6.66" lower="-3.49065850399" upper="3.49065850399" velocity="9.42477796077"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="armtwo_link">
      <visual>
        <geometry>
          <mesh filename="package://mitsubishi_manipulator_description/meshes/rv4frl/armtwo_link.STL"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://mitsubishi_manipulator_description/meshes/rv4frl/armtwo_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="0.15035 0.00012489 -0.00094895"/>
        <mass value="2.813"/>
        <inertia ixx="0.0054523" ixy="-0.00013638" ixz="-6.8603E-05" iyy="0.02079" iyz="-2.9135E-07" izz="0.019518"/>
      </inertial>
    </link>
    <joint name="joint5" type="revolute">
      <parent link="armtwo_link"/>
      <child link="wrist_link"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <axis xyz="0 0 -1"/>
      <limit effort="6.66" lower="-2.09439510239" upper="2.09439510239" velocity="10.8734012399"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="wrist_link">
      <visual>
        <geometry>
          <mesh filename="package://mitsubishi_manipulator_description/meshes/rv4frl/wrist_link.STL"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://mitsubishi_manipulator_description/meshes/rv4frl/wrist_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="-0.014155 0.0010374 2.0643E-05"/>
        <mass value="0.58693"/>
        <inertia ixx="0.00050552" ixy="1.5318E-05" ixz="2.0025E-07" iyy="0.00081074" iyz="-5.312E-07" izz="0.00090713"/>
      </inertial>
    </link>
    <joint name="joint6" type="revolute">
      <parent link="wrist_link"/>
      <child link="flange_link"/>
      <origin rpy="-3.1416 0 0" xyz="-0.085 0 0"/>
      <axis xyz="-1 0 0"/>
      <limit effort="3.96" lower="-6.28318530718" upper="6.28318530718" velocity="12.5663706144"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="flange_link">
      <visual>
        <geometry>
          <mesh filename="package://mitsubishi_manipulator_description/meshes/rv4frl/flange_link.STL"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://mitsubishi_manipulator_description/meshes/rv4frl/flange_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="0.009893 -0.00013419 -3.4246E-16"/>
        <mass value="0.018683"/>
        <inertia ixx="3.4376E-06" ixy="-1.49E-08" ixz="5.5391E-21" iyy="2.3475E-06" iyz="-3.6347E-20" izz="2.3076E-06"/>
      </inertial>
    </link>
    <joint name="ee_fixed_joint" type="fixed">
      <parent link="flange_link"/>
      <child link="ee_link"/>
      <origin rpy="0.0 0.0 1.57079632679" xyz="0.0 0.0 0.0"/>
    </joint>
    <link name="ee_link">
      <collision>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.01 0 0"/>
      </collision>
    </link>
    <!-- ROS base_link to UR 'Base' Coordinates transform -->
    <link name="base"/>
    <joint name="base_link-base_fixed_joint" type="fixed">
      <!-- NOTE: this rotation is only needed as long as base_link itself is
                   not corrected wrt the real robot (ie: rotated over 180
                   degrees)
        -->
      <origin rpy="0 0 -3.14159265359" xyz="0 0 0"/>
      <parent link="base_link"/>
      <child link="base"/>
    </joint>
    <!-- Frame coincident with all-zeros TCP on UR controller -->
    <link name="tool0"/>
    <joint name="flange_link-tool0_fixed_joint" type="fixed">
      <origin rpy="-1.57079632679 0 0" xyz="0 0.0 0"/>
      <parent link="flange_link"/>
      <child link="tool0"/>
    </joint>
    <link name="world"/>
    <joint name="world_joint" type="fixed">
      <parent link="world"/>
      <child link="base_link"/>
      <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
    </joint>
  </robot>
  `,
          packages: {
            mitsubishi_manipulator_description: 'https://storage.googleapis.com/kompose-artifacts/mitsubishi_manipulator_description',
          },
          last_modified: '2019-01-01T11:19:52.958376Z',
          last_modified_by: {
            userid: '123',
            username: 'guest4',
          },
          is_locked: false,
          locked_by: {
            userid: '123',
            username: 'guest4',
          },
        },
      },
    }
  },
  {
    name: 'Warehouse 2',
    ago: '20 hours',
    key: 'vcqD7cFggx',
    details: {
      data: {
        name: 'Japan post demo',
        dsl: `
      
      `,
        last_modified: '2019-01-01T11:28:56.197234Z',
        environment: {
          urdf: `<?xml version="1.0" ?>
  <robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">
    <material name="Grey">
      <color rgba="0.7 0.7 0.7 1.0"/>
    </material>
    <material name="GreyPallet">
      <color rgba="0.7 0.7 0.7 1.0"/>
    </material>
    <material name="Grey4">
      <color rgba="0.6 0.7 0.8 1.0"/>
    </material>
    <material name="Grey2">
      <color rgba="0.7 0.7 0.7 1.0"/>
    </material>
    <link name="root_link"/>
  </robot>`,
          packages: {
          },
          last_modified: '2019-01-01T11:19:52.958376Z',
          last_modified_by: {
            userid: '123',
            username: 'guest4',
          },
          is_locked: false,
          locked_by: {
            userid: '123',
            username: 'guest4',
          },
        },
      },
    }
  },
];

export const hardwareList = [
  {
    img: '/img/jptable.jpg',
    urdf: '/urdfs/table.urdf',
    packages: {
      rr_world_description: 'https://storage.googleapis.com/kompose-artifacts/rr_world_description',
    },
    name: 'JP table',
    key: 'asdfgh',
    up: '+Y',
    isCustom: true,
    ago: '20 hours',
  },
  {
    img: '/img/conveyor.jpg',
    urdf: '/urdfs/conveyor.urdf',
    packages: {
      rr_world_description: 'https://storage.googleapis.com/kompose-artifacts/rr_world_description',
    },
    name: 'Conveyor',
    key: 'asdf',
    up: '+Y',
    isCustom: true,
    ago: '20 hours',
  },
  {
    img: '/img/pallet.jpg',
    urdf: '/urdfs/pallet.urdf',
    packages: {
      rr_world_description: 'https://storage.googleapis.com/kompose-artifacts/rr_world_description',
    },
    name: 'Pallet',
    key: 'asdfg',
    up: '+Y',
    isCustom: true,
    ago: '20 hours',
  },
  {
    img: '/img/hw_ur10.jpg',
    name: 'Universal Robots UR10',
    urdf: '/ur10.urdf',
    packages: {
      ur_description: 'https://storage.googleapis.com/kompose-artifacts/ur_description',
    },
    key: 'r9DfPqMsHaasdsd23',
    up: '+Y',
    isCustom: true,
    ago: '20 hours',
    details: `#### Performance
  |              | 
      | ------------- |-------------
  | Repeatability             | ±0.1 mm / ±0.0039 in (4 mils)
  | Ambient temperature range | 0-50°      
  | Power consumption | Min 90W, Typical 250W, Max 500W    
  | Collaboration operation | 15 advanced adjustable safety functions. TüV NORD Approved Safety Function. Tested in accordance with: EN ISO 13849:2008 PL d    
  
  #### Specification
  |              | 
      | ------------- |-------------
  | Payload             | 10 kg /22 lbs
  | Reach | 1300 mm / 51.2 in
  | Degrees of freedom | 6 rotating joints
  | Programming | Polyscope graphical user interface on 12 inch touchscreen with mounting
  `,
  },
  {
    img: '/img/vacuum_gripper.jpg',
    urdf: '/urdfs/gripper.urdf',
    packages: {
      rr_world_description: 'https://storage.googleapis.com/kompose-artifacts/rr_world_description',
    },
    name: 'Schmalz suction gripper',
    key: 'a',
    up: '+Y',
    isCustom: true,
    ago: '20 hours',
  },
  {
    img: '/img/agv.jpg',
    urdf: '/urdfs/agv.urdf',
    packages: {
      rr_shared_world_description: 'https://storage.googleapis.com/kompose-artifacts/rr_shared_world_description',
    },
    name: 'AGV',
    key: 'asd',
    up: '+Y',
    isCustom: true,
    ago: '20 hours',
  },
  {
    img: '/img/hw_camera.png',
    name: 'Camera',
    urdf: '/camera.urdf',
    packages: {
      rr_world_description: 'https://storage.googleapis.com/kompose-artifacts/rr_world_description',
    },
    up: '-Y',
    key: 'r9DfPqMsH',
    isCustom: true,
    ago: '3 months',
  },
  {
    img: '/img/hw_gripper_2.jpg',
    name: 'Vacuum Gripper 10',
    urdf: '/vg10.urdf',
    packages: {
      rr_world_description: 'https://storage.googleapis.com/kompose-artifacts/rr_world_description',
    },
    up: '-Y',
    key: 'r9DfPqMsHaasdsd765',
    isCustom: true,
    ago: '2 months',
  },
  {
    img: '/img/hw_mitsubishi.jpg',
    name: 'Mitsubishi RV7FRL',
    urdf: '/mitsubishi_rv7frl.urdf',
    packages: {
      mitsubishi_manipulator_description: 'https://storage.googleapis.com/kompose-artifacts/mitsubishi_manipulator_description',
    },
    up: '+Y',
    key: 'r9DfPqMsHaasdsd',
    isCustom: true,
    ago: '2 minutes',
  },
];

export const softwareList = [
  {
    name: 'Vision Software',
    key: 'r9DfPqMsH',
    isCustom: true,
    ago: '20 hours',
    details: `1. Detects overlapping parts in 3D
  2. Detects parts in all colors
  3. Detects parts of most materials
  4. Works in changing and poor light conditions
  
  #### Exported algorithms:
  
  * Filtering
  * Template matching
  * Statistical outlier removal and many more
  
  [View Teach API documentation](https://www.google.com)  
  [View Detection API documentation](https://www.google.com)  
  Supported Cameras: [Ensenso](https://www.google.com), [Pickit](https://www.google.com)`,
  },
  {
    name: 'Motion planning',
    key: 'vcqD7cFggx',
    isCustom: false,
    ago: '20 hours',
    details: `1. Optimized trajectory for pick and place
  2. Supports picking moving objects
  3. Real time motion changes based on dynamic obstacles
  
  #### Exported Algorithm:
  
  * SBL
  * EST
  * LBKPIECE
  * BKPIECE
  * KPIECE
  * RRT
  * RRTConnect
  * RRTstar
  * TRRT
  * PRM
  * PRMstar
  * FMT
  * BFMT
  * PDST
  * STRIDE
  * BiTRRT
  * LBTRRT
  * BiEST
  * ProjEST
  * LazyPRM
  * LazyPRMstar
  * SPARS
  * SPARStwo
  
  [View API Documentation](https://www.google.com)`,
  },
  {
    name: 'Grasp Planning',
    key: 'asdf',
    isCustom: true,
    ago: '3 days',
    details: `1. Supports optimal grasps for two and three finger grippers
  2. Optimal suction points for a given object
  3. Database storage for faster grasp planning
  
  #### Exported Algorithms:
  
  * Primitive based grasp planning
  * Grasp planner based on force closure
  * Dynamics supported planning
  
  [View API Documentation](https://www.google.com)`,
  },
];
